### PR TITLE
Fix setup.py to install the oidc package

### PR DESCRIPTION
**Pull request by jzoldak**
@rlucioni @clintonb

### CODE REVIEW

**Comment by clintonb** [comment]
:+1: (A new release will be needed.)

**Comment by jzoldak** [comment]
@rlucioni do you have time to make a new release today? We can't create new jenkins workers until the new version is referenced in the edx-platform repo. The other option is that I can put in a PR to put the -e back in over there in the meantime.

**Comment by rlucioni** [comment]
@jzoldak sure. Could you bump the version in setup.py to 0.5.3 as part of this PR?

**Comment by jzoldak** [comment]
@rlucioni thx. I bumped up the version number and squashed.
I don't know what you guys want to do with the management and migration folders. Those won't be installed either. Did you want them to be?

**Comment by rlucioni** [comment]
@jzoldak good call; we definitely want access to the management commands in edx-platform.

Instead of listing the package names one by one, I'd suggest using setuptools' `find_packages` utility. Here's [an example](https://github.com/edx/auth-backends/blob/master/setup.py#L30) from one of our other repos which includes everything except for tests, which is what I'd do here.

**Comment by jzoldak** [comment]
@rlucioni Thx. I modified setup.py to use the exclude pattern. Does this PR look good then?

Couple things unrelated:
1. The exclude pattern over at the other repo excludes "tests" but doesn't actually exclude "auth_backends/tests". I'll put in a PR over there.
2. The coveralls config on this repo seems like it's not set up correctly.

**Comment by rlucioni** [comment]
:+1: 

1. Thanks, nice catch. I took a look.
2. Is there something in particular that seems off to you? I don't have permissions to modify Coveralls, but I'm all for correcting it. Thanks for fixing the Travis script.

**Pull request merged**
