### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by justinabrahms**

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @justinabrahms! I've created [OSPR-1079](https://openedx.atlassian.net/browse/OSPR-1079) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



You haven't added yourself to the [AUTHORS](https://github.com/edx/edx-oauth2-provider/blob/master/AUTHORS)      file for this repo. Please create a new pull request to do so!     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by clintonb** [comment]
:+1:

**Comment by nedbat** [comment]
@clintonb merge when you are ready.

**Comment by clintonb** [comment]
Merging, despite the broken build. I'm 99.9% certain the readme change is not affecting Django app loading. If it is, we've got far bigger problems than the typo.

**Pull request merged**
