### PR TITLE
Refrain from using get_user_model in management commands

### PR DESCRIPTION
**Pull request by rlucioni**
Support Django 1.4. @wedaly, please review. This resolves the issues you encountered earlier.

### CODE REVIEW

**Comment by wedaly** [comment]
:+1: Wow, you guys are really harsh with your coverage checks :)

**Comment by rlucioni** [comment]
:cry: We need to make Coveralls less sensitive for this repo. @jzoldak, if you have a moment, could you match the Coveralls settings for this repo with those for edx/ecommerce?

**Comment by jzoldak** [comment]
@rlucioni It looks like both this repo and edx/ecommerce have the "COVERAGE DECREASE THRESHOLD FOR FAILURE" field unfilled, which from my googling around seems to default as 0. So any decrease in coverage percentage will fail the coverage context.

Looking in the history of the edx/ecommerce coveralls builds, I do see [this build](https://coveralls.io/builds/3047181) however that reduced the coverage by 0.004%, so I can't tell you why it didn't fail that context in [the pr](https://github.com/edx/ecommerce/pull/199). Maybe the threshold was set to something else at the time?

What do you guys want the thresholds set at? 
* COVERAGE THRESHOLD FOR FAILURE
* COVERAGE DECREASE THRESHOLD FOR FAILURE

**Comment by rlucioni** [comment]
@jzoldak could we set COVERAGE THRESHOLD FOR FAILURE at 95% and COVERAGE DECREASE THRESHOLD FOR FAILURE at 1%?

**Comment by jzoldak** [comment]
@rlucioni done (for both repos)

**Comment by rlucioni** [comment]
Thank you very much @jzoldak.

**Pull request merged**
